set.seed(1)
library(MASS)
attach(Boston)

#(a)#
m3 <- lm(nox~poly(dis,3),data=Boston)
summary(m3)

dislims <- range(dis)
dis.grid <- seq(from=dislims[1],to=dislims[2])

pred <- predict(m3,newdata=list(dis=dis.grid),se=T)

plot(dis,nox,col="gray")
title("Cubic Polynomial Fit")
lines(dis.grid,pred$fit,lwd=2,col="red")
lines(dis.grid,pred$fit+2*pred$se,lty="dashed")
lines(dis.grid,pred$fit-2*pred$se,lty="dashed")

#(b)#
plot(dis,nox,col="gray")
title("Various Polynomial Fits")
m1 <- lm(nox~dis,data=Boston)
pred <- predict(m1,newdata=list(dis=dis.grid),se=T)
lines(dis.grid,pred$fit,lwd=2,col="orange")
m2 <- lm(nox~poly(dis,2),data=Boston)
pred <- predict(m2,newdata=list(dis=dis.grid),se=T)
lines(dis.grid,pred$fit,lwd=2,col="green")
m4 <- lm(nox~poly(dis,4),data=Boston)
pred <- predict(m4,newdata=list(dis=dis.grid),se=T)
lines(dis.grid,pred$fit,lwd=2,col="blue")
m5 <- lm(nox~poly(dis,5),data=Boston)
pred <- predict(m5,newdata=list(dis=dis.grid),se=T)
lines(dis.grid,pred$fit,lwd=2,col="purple")
m6 <- lm(nox~poly(dis,6),data=Boston)
pred <- predict(m6,newdata=list(dis=dis.grid),se=T)
lines(dis.grid,pred$fit,lwd=2,col="black")
m7 <- lm(nox~poly(dis,7),data=Boston)
pred <- predict(m7,newdata=list(dis=dis.grid),se=T)
lines(dis.grid,pred$fit,lwd=2,col="gray")
m8 <- lm(nox~poly(dis,8),data=Boston)
pred <- predict(m8,newdata=list(dis=dis.grid),se=T)
lines(dis.grid,pred$fit,lwd=2,col="magenta")
m9 <- lm(nox~poly(dis,9),data=Boston)
pred <- predict(m9,newdata=list(dis=dis.grid),se=T)
lines(dis.grid,pred$fit,lwd=2,col="yellow")
m10 <- lm(nox~poly(dis,10),data=Boston)
pred <- predict(m10,newdata=list(dis=dis.grid),se=T)
lines(dis.grid,pred$fit,lwd=2,col="gold")
legend("topright",legend=c("^1","^2","^3","^4","^5","^6","^7","^8","^9","^10"),
       col=c("orange","green","red","blue","purple","black","gray","magenta","yellow","gold"),
       lty=1,lwd=2,cex=.8)

rsslist <- list(sum(m1$residuals^2),sum(m2$residuals^2),sum(m3$residuals^2),sum(m4$residuals^2),
              sum(m5$residuals^2),sum(m6$residuals^2),sum(m7$residuals^2),sum(m8$residuals^2),
              sum(m9$residuals^2),sum(m10$residuals^2))
as.numeric(rsslist)

#(c)#
library(caret)
library(elasticnet)
set.seed(1)
train.control <- trainControl(method = "repeatedcv", number = 10,repeats=3)
mcv1 <- train(nox~dis,data=Boston,method ="lm",trControl=train.control)
mse1 <- (mcv1$results$RMSE^2)
mcv2 <- train(nox~poly(dis,2),data=Boston,method ="lm",trControl=train.control)
mse2 <- (mcv2$results$RMSE^2)
mcv3 <- train(nox~poly(dis,3),data=Boston,method ="lm",trControl=train.control)
mse3 <- (mcv3$results$RMSE^2)
mcv4 <- train(nox~poly(dis,4),data=Boston,method ="lm",trControl=train.control)
mse4 <- (mcv4$results$RMSE^2)
mcv5 <- train(nox~poly(dis,5),data=Boston,method ="lm",trControl=train.control)
mse5 <- (mcv5$results$RMSE^2)
mcv6 <- train(nox~poly(dis,6),data=Boston,method ="lm",trControl=train.control)
mse6 <- (mcv6$results$RMSE^2)
mcv7 <- train(nox~poly(dis,7),data=Boston,method ="lm",trControl=train.control)
mse7 <- (mcv7$results$RMSE^2)
mcv8 <- train(nox~poly(dis,8),data=Boston,method ="lm",trControl=train.control)
mse8 <- (mcv8$results$RMSE^2)
mcv9 <- train(nox~poly(dis,9),data=Boston,method ="lm",trControl=train.control)
mse9 <- (mcv9$results$RMSE^2)
mcv10 <- train(nox~poly(dis,10),data=Boston,method ="lm",trControl=train.control)
mse10 <- (mcv10$results$RMSE^2)
mselist <- list(mse1,mse2,mse3,mse4,mse5,mse6,mse7,mse8,mse9,mse10)
as.matrix(mselist)

plot(dis,nox,col="gray")
title("Degree 3 vs. Degree 4 polynomial fit")
m3 <- lm(nox~poly(dis,3),data=Boston)
pred <- predict(m3,newdata=list(dis=dis.grid),se=T)
lines(dis.grid,pred$fit,lwd=2,col="red")
m4 <- lm(nox~poly(dis,4),data=Boston)
pred <- predict(m4,newdata=list(dis=dis.grid),se=T)
lines(dis.grid,pred$fit,lwd=2,col="blue")
legend("topright",legend=c("^3","^4"),col=c("red","blue"),lty=1,lwd=2,cex=.8)

#(d)#
library(splines)
s1 <- lm(nox~bs(dis,df=4),data=Boston)
sum(s1$residuals^2)
pred <- predict(s1,newdata=list(dis=dis.grid),se=T)
plot(dis,nox,col="gray")
lines(dis.grid,pred$fit,lwd=2,col="red")
abline(v=c(3.207),lty=2,col="gray")
title("Regression spline, df=4")
lines(dis.grid,pred$fit+2*pred$se,lty="dashed")
lines(dis.grid,pred$fit-2*pred$se,lty="dashed")
attr(bs(dis,df=4),"knots")

#(e)#
plot(dis,nox,col="gray")
title("Regression spline for various df values")
s2 <- lm(nox~bs(dis,df=6),data=Boston)
pred <- predict(s2,newdata=list(dis=dis.grid),se=T)
lines(dis.grid,pred$fit,lwd=2,col="red")
s3 <- lm(nox~bs(dis,df=8),data=Boston)
pred <- predict(s3,newdata=list(dis=dis.grid),se=T)
lines(dis.grid,pred$fit,lwd=2,col="blue")
s4 <- lm(nox~bs(dis,df=10),data=Boston)
pred <- predict(s4,newdata=list(dis=dis.grid),se=T)
lines(dis.grid,pred$fit,lwd=2,col="green")
s5 <- lm(nox~bs(dis,df=12),data=Boston)
pred <- predict(s5,newdata=list(dis=dis.grid),se=T)
lines(dis.grid,pred$fit,lwd=2,col="black")
s6 <- lm(nox~bs(dis,df=14),data=Boston)
pred <- predict(s6,newdata=list(dis=dis.grid),se=T)
lines(dis.grid,pred$fit,lwd=2,col="orange")
s7 <- lm(nox~bs(dis,df=16),data=Boston)
pred <- predict(s7,newdata=list(dis=dis.grid),se=T)
lines(dis.grid,pred$fit,lwd=2,col="purple")
s8 <- lm(nox~bs(dis,df=18),data=Boston)
pred <- predict(s8,newdata=list(dis=dis.grid),se=T)
lines(dis.grid,pred$fit,lwd=2,col="gold")
legend("topright",legend=c("df=6","df=8","df=10","df=12","df=14","df=16","df=18"),
       col=c("red","blue","green","black","orange","purple","gold"),
       lty=1,lwd=2,cex=.8)
rsslist2 <- list(sum(s2$residuals^2),sum(s3$residuals^2),sum(s4$residuals^2),sum(s5$residuals^2),
                 sum(s6$residuals^2),sum(s7$residuals^2),sum(s8$residuals^2))
as.matrix(rsslist2)

#(f)#
plot(dis,nox,col="gray")
title("Smoothing Spline")
ss <- smooth.spline(dis,nox,cv=TRUE)
ss$df
pred <- predict(ss,newdata=list(dis=dis.grid),se=T)
lines(ss,lwd=2,col="red")
ss2 <- smooth.spline(dis,nox,cv=FALSE)
ss2$df
pred <- predict(ss2,newdata=list(dis=dis.grid),se=T)
lines(ss2,lwd=2,col="blue")
